name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup MSBuild
        uses: warrenbuckley/Setup-MSBuild@v1
        
      - name: Cache npm modules
        uses: actions/cache@v1
        with:
          path: ~\AppData\Roaming\npm-cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Cache NuGet packages
        uses: actions/cache@v1
        with:
          path: ~\.nuget\packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
            
      - name: Install dependencies
        working-directory: ./ScoreSaberWidget
        run: msbuild -t:Restore
      - name: Build ScoreSaberWidget
        working-directory: ./ScoreSaberWidget
        run: msbuild -t:SignAndroidPackage -p:Configuration=Release
        
      - name: Rename APK
        run: copy .\ScoreSaberWidget\bin\Release\com.sc2ad.ScoreSaberWidget-Signed.apk .\com.sc2ad.ScoreSaberWidget.apk
      - name: Upload ScoreSaberWidget
        uses: actions/upload-artifact@v1
        with:
          name: com.sc2ad.ScoreSaberWidget.apk
          path: ./com.sc2ad.ScoreSaberWidget.apk
